apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will listen
      targetPort: 5000  # Port on which the Flask app is running inside the pods
  type: LoadBalancer




  kubectl create secret docker-registry dockerhub-secret \
--docker-username=prajwalpb \
--docker-password=123456789pb \
--docker-email=custompb99@gmail.com